FAIL
Kernel panic in run: PANIC at ../../threads/interrupt.c:361 in intr_handler(): Unexpected interrupt
Call stack: 0x800420e332 0x8004207a2d 0x8004207bac 0x800420e597 0x800420e6b3 0x800420ed92 0x80042086c3 0x800420e6bf 0x800420ed92 0x8004208967 0x8004211cf0 0x800421067e 0x8004206036 0x8004206474
Translation of call stack:
0x000000800420e332: debug_panic (lib/kernel/debug.c:32)
0x0000008004207a2d: intr_handler (threads/interrupt.c:365)
0x0000008004207bac: intr_entry (threads/intr-stubs.o:?)
0x000000800420e597: list_prev (lib/kernel/list.c:106)
0x000000800420e6b3: find_end_of_run (lib/kernel/list.c:348)
0x000000800420ed92: list_sort (lib/kernel/list.c:402)
0x00000080042086c3: sema_less_func (threads/synch.c:69)
0x000000800420e6bf: find_end_of_run (lib/kernel/list.c:348)
0x000000800420ed92: list_sort (lib/kernel/list.c:402)
0x0000008004208967: sema_up (threads/synch.c:140)
0x0000008004211cf0: test_priority_donate_sema (tests/threads/priority-donate-sema.c:46)
0x000000800421067e: run_test (tests/threads/tests.c:61)
0x0000008004206036: run_task (threads/init.c:237)
0x0000008004206474: run_actions (threads/init.c:282)
